$('.vegas').vegas({
  overlay: true,
  transition: 'fade',
  transitionDuration: 2500,
  delay: 3500,
  animation: 'random',
  animationDuration: 5000,
  timer: true,
  shuffle: true,
  cover: true,
  color: '#202020',
  slides: [
    { src: 'img/99marlin.jpg' },
    { src: 'img/albino2.png' },
    { src: 'img/albino.jpg' },
    { src: 'img/billfish.jpg' },
    { src: 'img/black.jpg' },
    { src: 'img/bmarlin.jpg' },
    { src: 'img/guat-e-marlin.jpg' },
    { src: 'img/hooked.jpg' },
    { src: 'img/jumper.jpg' },
    { src: 'img/mako.jpg' },
    { src: 'img/mozambique.jpg' },
    { src: 'img/sinking.jpg' },
    { src: 'img/panama.jpg' },
    { src: 'img/south-florida.jpg' },
    { src: 'img/7.jpg' },
    { src: 'img/backflip.png' },
    { src: 'img/bigtuna.jpg' },
    { src: 'img/blackmarlin.jpg' },
    { src: 'img/blue-running.png' },
    { src: 'img/blue-trolling.png' },
    { src: 'img/blue.jpg' },
    { src: 'img/blue1.jpg' },
    { src: 'img/burnin.jpg' },
    { src: 'img/crowsview.jpg' },
    { src: 'img/deep-sea-charter-fishing.jpg' },
    { src: 'img/deep-sea-fishing.jpg' },
    { src: 'img/dolphin.jpg' },
    { src: 'img/dscf.jpg' },
    { src: 'img/fight.jpg' },
    { src: 'img/fighting-dolphin.jpg' },
    { src: 'img/fishing.jpg' },
    { src: 'img/fishon.jpg' },
    { src: 'img/flip.png' },
    { src: 'img/from-above.png' },
    { src: 'img/hatteras-yacht.jpg' },
    { src: 'img/heavyseas.jpg' },
    { src: 'img/hooks.jpg' },
    { src: 'img/humdinger.jpg' },
    { src: 'img/island.jpg' },
    { src: 'img/jumping-sailfish.jpg' },
    { src: 'img/killer.jpg' },
    { src: 'img/mackeral.jpg' },
    { src: 'img/marina.jpg' },
    { src: 'img/marlin.jpg' },
    { src: 'img/miami.jpg' },
    { src: 'img/offshore-fishing.png' },
    { src: 'img/open-water.png' },
    { src: 'img/pacific-sailfish.jpg' },
    { src: 'img/racing.jpg' },
    { src: 'img/reel-while-running.png' },
    { src: 'img/the-keys.png' },
    { src: 'img/picture_31.png' },
    { src: 'img/penn-reels.png' },
    { src: 'img/showingoff.jpg' },
    { src: 'img/sick.jpg' },
    { src: 'img/sinking.jpg' },
    { src: 'img/snagged.jpg' },
    { src: 'img/sport-fish.jpg' },
    { src: 'img/sportfishers.jpg' },
    { src: 'img/storm2.jpg' },
    { src: 'img/sunset.png' },
    { src: 'img/teasers.jpg' },
  ],
  overlay: "/js/vegas/dist/overlays/09.png"
});
